### ISSUE TITLE
写合约时，有时候点击右键无法出现下拉框

### ISSUE THREAD

**Issue by leeduckgo** [WeBankBlockchain/WeBASE-Front#501]
下拉框在点击部分文件夹/合约时无法出现。
是在服务器上安装的WeBase，但是在Mac环境上访问的
<img width="149" alt="WechatIMG10121" src="https://user-images.githubusercontent.com/12784118/102561168-f58df180-410e-11eb-9bea-2972ab94d0a4.png">
<img width="221" alt="WechatIMG10119" src="https://user-images.githubusercontent.com/12784118/102561175-f7f04b80-410e-11eb-93b8-312401973991.png">

**Comment by mingzhenliu** [comment]
对template限制出现了漏洞，1.4.3限制template里面新建文件
