### ISSUE TITLE
启动失败却提示启动成功。

### ISSUE THREAD

**Issue by 99Kies** [WeBankBlockchain/WeBASE-Front#504]

**Comment by CodingCattwo** [comment]
需要根据日志是否输出“run success”，或检查WeBASE-Front端口是否已启用来确认启动成功

**Comment by 99Kies** [comment]
不好意思，忘记close issue了。
记录一下问题：
启动失败，却提示启动成功，而且log日志中也没有任何报错。
这个时候更多原因是因为机器内存不够导致的启动失败。
java web 服务 差不多一个服务留1G的运行内存。
