### ISSUE TITLE
启动失败，报与Tomcat相关的错误

### ISSUE THREAD

**Issue by treeforest** [WeBankBlockchain/WeBASE-Front#619]
错误日志：Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'httpPutFormContentFilter' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.filter.OrderedHttpPutFormContentFilter]: Factory method 'httpPutFormContentFilter' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.springframework.http.MediaType

场景：搭建WeBase平台的时候启动错误
环境：使用Windows的wsl(ubuntu)

**Comment by CodingCattwo** [comment]
需要更详细的错误信息，或检查一下对应tomcat版本在WSL的Ubuntu的适配性

**Comment by treeforest** [comment]
收到了，谢谢~~
