### ISSUE TITLE
mysql 5.7.9,jdk8。安装以后，webase-front起不来

### ISSUE THREAD

**Issue by bjzhangyong** [WeBankBlockchain/WeBASE-Front#634]
[WeBASE-Front-error.log](https://github.com/WeBankFinTech/WeBASE-Front/files/6897457/WeBASE-Front-error.log)
[WeBASE-Front.log](https://github.com/WeBankFinTech/WeBASE-Front/files/6897458/WeBASE-Front.log)
[error.log](https://github.com/WeBankFinTech/WeBASE-Front/files/6897459/error.log)
看front的错误信息如下，请问是什么问题。
PS：换了JDK11之后就一路顺利，没问题了。

2021-07-24 08:03:42.832 [main] ERROR SpringApplication() - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'contractService': Unsatisfied dependency expressed through field 'transService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transService': Unsatisfied dependency expressed through field 'web3ApiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'web3ApiService': Unsatisfied dependency expressed through field 'bcosSDK'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getBcosSDK' defined in class path resource [com/webank/webase/front/base/config/Web3Config.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.fisco.bcos.sdk.BcosSDK]: Factory method 'getBcosSDK' threw exception; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library

**Comment by CodingCattwo** [comment]
推荐使用oracle jdk
webase-front中未使用mysql服务

**Comment by VSEJGFB** [comment]
> 推荐使用oracle jdk webase-front中未使用mysql服务

我使用Oracle jdk13也报同样的错：
```
bcos@bcos-virtual-machine:~/fisco3.2/webase-front$ $JAVA_HOME
bash: /usr/lib/jvm/jdk-13: Is a directory
bcos@bcos-virtual-machine:~/fisco3.2/webase-front$ /usr/lib/jvm/jdk-13/bin/java -version
java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)
bcos@bcos-virtual-machine:~/fisco3.2/webase-front$ bash start.sh
===============================================================================================
Server com.webank.webase.front.Application Port 5002 ...PID(8094) [Starting]. Please check message through the log file (default path:./log/).
===============================================================================================
bcos@bcos-virtual-machine:~/fisco3.2/webase-front$ bash status.sh
===============================================================================================
Server com.webank.webase.front.Application Port 5002 is not running
===============================================================================================
bcos@bcos-virtual-machine:~/fisco3.2/webase-front$ cat log/WeBASE-Front-error.log 
2023-06-07 11:17:05.361 [main] ERROR SpringApplication() - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'contractService': Unsatisfied dependency expressed through field 'transService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transService': Unsatisfied dependency expressed through field 'web3ApiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'web3ApiService': Unsatisfied dependency expressed through field 'bcosSDK'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getBcosSDK' defined in class path resource [com/webank/webase/front/base/config/Web3Config.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.fisco.bcos.sdk.BcosSDK]: Factory method 'getBcosSDK' threw exception; nested exception is org.fisco.bcos.sdk.BcosSDKException: create BcosSDK failed, error info: init channel network error!
org.fisco.bcos.sdk.network.NetworkException: 
...
```
