### ISSUE TITLE
关于时间戳的一些问题

### ISSUE THREAD

**Issue by llkhs** [WeBankBlockchain/WeBASE-Front#785]
主要问题：请问内置编译器获取时间戳是从哪一天开始计算得来的呢

背景：
Solidity 提供了一些自带的时间单位来处理时间，比如变量 now 将返回当前的unix时间戳（自1970年1月1日以来经过的秒数）。比如2020年1月1日的 unix 时间戳是 1577836800。

- [x] 2022.07.15 16:49:00 在[Remix IDE](remix.ethereum.org)里，获取 `now` 或者 `block.timestamp` 得到 `1657874940`，经简单年运算 `1657874940 / 31536000 + 1970`  得到 `2022` 是正确的**时间结果**。

- [ ] 但 2022.07.15 16:45:00 在[WeBASE-Front](https://webasedoc.readthedocs.io/zh_CN/latest/docs/WeBASE-Install/developer.html) **内置合约IDE部署**获取 `now` 或者 `block.timestamp` 得到 `1657874679966`，经运算后得到`54505`不是理想的结果。

版本：
节点控制台 (2.8.0)，buildTime='20210830 12:52:15',
WeBASE-Front：v1.5.4/webase-front.zip
fisco：v2.9.0
ubuntu 20.04

系统时间：
```
root@ecs-219067:~# uptime -s
2022-07-15 16:46:15
```

**Comment by CodingCattwo** [comment]
FISCO BCOS的合约中的timestamp为ms毫秒格式，多了三位数
